name: CMake Multi-Platform Build and Release

on:
  push:
    tags:
      - 'v*'    # Triggers on version tags like v1.0.0
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            artifact_name: windows-binary
            output_path: build/Release/calc.exe
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            artifact_name: linux-binary
            output_path: build/calc
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            artifact_name: linux-binary
            output_path: build/calc
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set output path
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.output_path }}

  release:
    name: "Create GitHub Release"
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Windows Artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-binary
        path: ./windows

    - name: Download Linux Artifact
      uses: actions/download-artifact@v3
      with:
        name: linux-binary
        path: ./linux

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./windows/calc.exe
          ./linux/calc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
